student_registration_app/config/routes.rb
Rails.application.routes.draw do
  resources :students
  root "students#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

student_registration_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

student_registration_app/app/models/student.rb
class Student < ApplicationRecord
end

student_registration_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

student_registration_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_path, notice: "Student was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:enrollment_number, :first_name, :last_name, :date_of_birth, :email, :phone)
    end
end

student_registration_app/app/helpers/application_helper.rb
module ApplicationHelper
end

student_registration_app/app/helpers/students_helper.rb
module StudentsHelper
end

student_registration_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentRegistrationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
      <%= yield %>
    <%=render "shared/footer" %>
  </body>
</html>

student_registration_app/app/views/shared/_footer.html.erb
<footer style="background:#004080; color:white; text-align:center; padding:15px; width:100%;
               position:fixed; bottom:0; left:0;">
  <span>Address : </span>
  <span style="margin:5px 0 0; font-size:12px;">
    Survey No. 58, Indrayani Nagar, Handewadi Road, Hadapsar, Pune
  </span>
</footer>

student_registration_app/app/views/shared/_header.html.erb
<header style="text-align:center; background:#004080; color:white; width:100%; padding:20px 10px; position:fixed; top:0; left:0;">
  <h1 style="margin:0; font-size:28px;">
    JSPM's Jayawantrao Sawant College of Engineering (JSCOE)
  </h1>
</header>

student_registration_app/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :enrollment_number, style: "display: block" %>
    <%= form.text_field :enrollment_number %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

student_registration_app/app/views/students/_student.html.erb
<div id="<%= dom_id student %>" 
     style="border:1px solid #ddd; border-radius:10px; padding:15px; margin-bottom:15px; 
            box-shadow:0 2px 6px rgba(0,0,0,0.1); background:white;">
  <p>
    <strong>Enrollment number:</strong>
    <%= student.enrollment_number %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= student.date_of_birth %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

</div>

student_registration_app/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

student_registration_app/app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

student_registration_app/app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

student_registration_app/app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>